--QUESTION NUMBER : 1
SELECT * FROM HOTEL;

--QUESTION NUMBER : 2
SELECT * FROM HOTEL WHERE STATUS=5 AND CITY IN ('KOLKATA', 'SALT LAKE');

--QUESTION NUMBER : 3
SELECT * FROM GUEST
WHERE (GUESTNAME LIKE 'S%' OR GUESTNAME LIKE 'A%');

--QUESTION NUMBER : 4
SELECT GUESTNAME FROM GUEST
WHERE (GUESTNAME NOT LIKE 'N%' AND GUESTNAME NOT LIKE 'H%' AND GUESTNAME NOT LIKE 'A%');

--QUESTION NUMBER : 5
SELECT GUESTNAME, GUESTADDRESS 
FROM GUEST
ORDER BY GUESTADDRESS;

--QUESTION NUMBER : 7
SELECT GUESTNO FROM BOOKING 
GROUP BY GUESTNO 
HAVING COUNT(*)=1;

--QUESTION NUMBER : 8
SELECT ROOMNO, TYPE FROM ROOM
WHERE RATE BETWEEN 3000 AND 4000;

--QUESTION NUMBER : 9
SELECT * FROM ROOM
WHERE RATE BETWEEN 3000 AND 4500;

--QUESTION NUMBER : 10
SELECT * FROM ROOM
WHERE (RATE < 4000 AND BED='DOUBLE')
ORDER BY RATE;

--QUESTION NUMBER : 11
SELECT HOTELNO FROM BOOKING
WHERE (DATEFROM >= '1-MAR-2014' AND DATEFROM < '1-APR-2014');

--QUESTION NUMBER : 12
SELECT * FROM BOOKING
WHERE DATETO IS NULL;

--QUESTION NUMBER : 13
UPDATE ROOM
SET RATE=RATE*1.1;

--QUESTION NUMBER : 14
DROP TABLE VISITORS;
DROP TABLE CORPORATES;

CREATE TABLE VISITORS AS (SELECT * FROM GUEST WHERE 1=0);

INSERT INTO VISITORS VALUES ('G001', 'NAREN KUMAR', 'M', 'AODPN8133Q', 'DELHI', 2);
INSERT INTO VISITORS VALUES ('G002', 'AMRITA ROY', 'F', 'AEWPM7385L', 'BANGALORE', 2);
INSERT INTO VISITORS VALUES ('G003', 'SAIKAT SINHA', 'M', 'APWKL2532Q', 'HYDERABAD', 2);

--QUESTION NUMBER : 15
ALTER TABLE VISITORS
RENAME TO CORPORATES;


