/*
PLSQL ASSIGNMENT - 01
WRITE PLSQL CODE THAT WILL FIND MAXIMUM OF TWO NUMBERS AND THAT VALUE WILL BE TAKEN BY USER.
*/

DECLARE
	A	NUMBER(5);
	B	NUMBER(5);
BEGIN
	A:=&A;
	B:=&B;
	IF A>B THEN
		DBMS_OUTPUT.PUT_LINE('MAXIMUM IS : '||A);
	ELSE
		DBMS_OUTPUT.PUT_LINE('MAXIMUM IS : '||B);
	END IF;
END;

/*
PLSQL ASSIGNMENT - 02
WRITE PLSQL CODE To show First 10 Fibonacci Numbers using the loop (Simple Lopp) .
*/

DECLARE
	A 	NUMBER(3) := 0;
	B 	NUMBER(3) := 1;
	C 	NUMBER(3) := 0;
	I 	NUMBER(3) := 1;
BEGIN
	LOOP
		DBMS_OUTPUT.PUT_LINE(A);
		C:=A+B;
		A:=B;
		B:=C;
		I:=I+1;
		EXIT WHEN I>10;
	END LOOP;
END;


