--GROUPING

--QUESTION NUMBER : 32
SELECT H.HOTELNAME, COUNT(*) AS "TOTAL_ROOMS"
FROM HOTEL H, ROOM R
WHERE (H.HOTELNO=R.HOTELNO)
GROUP BY H.HOTELNAME;

--QUESTION NUMBER : 33
SELECT H.CITY, R.TYPE, COUNT(*) AS "TOTAL_ROOMS"
FROM HOTEL H, ROOM R
WHERE (H.HOTELNO=R.HOTELNO)
GROUP BY H.CITY, R.TYPE;

--QUESTION NUMBER : 34
SELECT H.HOTELNAME, COUNT(*) AS "TOTAL_AC_ROOMS"
FROM HOTEL H, ROOM R
WHERE (H.HOTELNO=R.HOTELNO AND H.CITY='KOLKATA' AND R.TYPE='AC')
GROUP BY H.HOTELNAME;

--QUESTION NUMBER : 35
SELECT H.HOTELNAME, COUNT(*) AS "AVG_ROOMS_BOOKED"
FROM HOTEL H, BOOKING B
WHERE (H.HOTELNO=B.HOTELNO AND (EXTRACT(MONTH FROM B.DATEFROM)=3))
GROUP BY H.HOTELNAME;

--QUESTION NUMBER : 36
CREATE TABLE TEMP1 AS (
	SELECT H.HOTELNAME, R.TYPE, COUNT(*) AS "COUNT"
	FROM HOTEL H, BOOKING B, ROOM R
	WHERE (H.HOTELNO=B.HOTELNO AND B.ROOMNO=R.ROOMNO AND H.CITY='KOLKATA')
	GROUP BY H.HOTELNAME, R.TYPE
);

SELECT T1.HOTELNAME, T1.TYPE
FROM TEMP1 T1
WHERE (T1.COUNT>=(SELECT MAX(T2.COUNT) FROM TEMP1 T2 WHERE T2.HOTELNAME=T1.HOTELNAME))
;

DROP TABLE TEMP1;

--QUESTION NUMBER : 37
SELECT H.HOTELNAME, SUM(R.RATE) AS "LOSS_INCOME"
FROM HOTEL H, ROOM R, BOOKING B
WHERE (H.HOTELNO=B.HOTELNO AND B.ROOMNO=R.ROOMNO AND (SYSDATE NOT BETWEEN B.DATEFROM AND B.DATETO))
GROUP BY H.HOTELNAME;

--QUESTION NUMBER : 38
SELECT H.HOTELNAME, H.HOTELNO, MIN(R.RATE)
FROM HOTEL H, ROOM R, BOOKING B
WHERE (H.HOTELNO=B.HOTELNO AND B.ROOMNO=R.ROOMNO)
GROUP BY H.HOTELNAME, H.HOTELNO;

--QUESTION NUMBER : 39
SELECT H.HOTELNAME, G.SEX, SUM(R.RATE) AS "EARNED"
FROM HOTEL H, BOOKING B, GUEST G, ROOM R
WHERE (H.HOTELNO=B.HOTELNO AND B.ROOMNO=R.ROOMNO AND G.GUESTNO=B.GUESTNO)
GROUP BY H.HOTELNAME, G.SEX;

-- VIEW

--QUESTION NUMBER : 01
CREATE TABLE ARCHIEVE_RECORDS AS (
	SELECT * FROM BOOKING
	WHERE 1<>1
);

INSERT INTO ARCHIEVE_RECORDS 
SELECT * 
FROM BOOKING
WHERE (DATEFROM < '01-FEB-2014');

SELECT * FROM ARCHIEVE_RECORDS;
DROP TABLE ARCHIEVE_RECORDS;

--QUESTION NUMBER : 02
CREATE VIEW HOTEL_GUEST_DET AS (
	SELECT H.HOTELNAME, G.GUESTNAME
	FROM HOTEL H, GUEST G, BOOKING B
	WHERE (H.HOTELNO=B.HOTELNO AND B.GUESTNO=G.GUESTNO) 
);

SELECT * FROM HOTEL_GUEST_DET;
DROP VIEW HOTEL_GUEST_DET;

--QUESTION NUMBER : 03
CREATE VIEW TAJ_GUEST_DET AS (
SELECT H.HOTELNAME, G.GUESTNO, G.GUESTNAME
FROM HOTEL H, GUEST G, BOOKING B
WHERE (H.HOTELNAME='THE TAJ BENGAL' AND H.HOTELNO=B.HOTELNO AND B.GUESTNO=G.GUESTNO)
);

SELECT * FROM TAJ_GUEST_DET;
DROP VIEW TAJ_GUEST_DET;





