--SUBQUERIES AND JOINS

--QUESTION NUMBER : 20
SELECT SUM(R.RATE) AS "DOUBLE_BED_H004"
FROM ROOM R, BOOKING B
WHERE (R.BED='DOUBLE' AND R.ROOMNO=B.ROOMNO AND R.HOTELNO='H004');

--QUESTION NUMBER : 21 
SELECT R.ROOMNO, R.TYPE, R.RATE
FROM ROOM R, HOTEL H
WHERE (H.HOTELNAME='HYATT' AND H.HOTELNO=R.HOTELNO);

--QUESTION NUMBER : 22
SELECT H.HOTELNAME, R.ROOMNO, R.TYPE
FROM ROOM R, HOTEL H
WHERE (H.HOTELNO=R.HOTELNO);

--QUESTION NUMBER : 23
SELECT H.HOTELNAME, B.DATEFROM, R.ROOMNO
FROM ROOM R, HOTEL H, BOOKING B
WHERE (R.TYPE='AC' AND H.CITY='KOLKATA' AND H.HOTELNO=R.HOTELNO AND B.ROOMNO=R.ROOMNO);

--QUESTION NUMBER : 24 
SELECT G.GUESTID
FROM HOTEL H, BOOKING B, GUEST G
WHERE (H.HOTELNAME='THE TAJ BENGAL' AND G.SEX='M' AND H.HOTELNO=B.HOTELNO AND B.GUESTNO=G.GUESTNO);

--QUESTION NUMBER : 25
SELECT H.HOTELNAME, R.ROOMNO, R.BED
FROM HOTEL H, ROOM R
WHERE (H.STATUS IN (3,5) AND H.HOTELNO=R.HOTELNO AND R.ROOMNO NOT IN (SELECT ROOMNO FROM BOOKING));

--QUESTION NUMBER : 26
SELECT H.HOTELNAME, H.CITY, MAX(R.RATE)
FROM HOTEL H, ROOM R
WHERE (H.HOTELNO=R.HOTELNO AND R.RATE=(SELECT MAX(RATE) FROM ROOM))
GROUP BY H.HOTELNAME, H.CITY;

--QUESTION NUMBER : 27
SELECT G.GUESTNO
FROM GUEST G, BOOKING B, HOTEL H
WHERE (G.NOMEMBER=1 AND H.HOTELNAME='THE PARK' AND (ABS(B.DATEFROM-B.DATETO) >2 ) AND H.HOTELNO=B.HOTELNO AND G.GUESTNO=B.GUESTNO);

--QUESTION NUMBER : 28
SELECT R.ROOMNO, R.BED, R.TYPE, G.GUESTNAME, G.NOMEMBER
FROM GUEST G, BOOKING B, HOTEL H, ROOM R
WHERE (H.HOTELNAME='HYATT' AND H.HOTELNO=B.HOTELNO AND G.GUESTNO=B.GUESTNO AND R.ROOMNO=B.ROOMNO);

--QUESTION NUMBER : 29
SELECT SUM(R.RATE) AS "TOTAL_INCOME_TAJ"
FROM BOOKING B, HOTEL H, ROOM R
WHERE (H.HOTELNAME='THE TAJ BENGAL' AND (EXTRACT(MONTH FROM B.DATEFROM) IN (1, 2)) AND B.HOTELNO=H.HOTELNO AND B.ROOMNO=R.ROOMNO);

--QUESTION NUMBER : 30 
SELECT DISTINCT R.ROOMNO AS "UNOCCUPIED_ORCHID"
FROM BOOKING B, HOTEL H, ROOM R
WHERE (H.HOTELNAME='ORCHID' AND (EXTRACT(MONTH FROM B.DATEFROM)!=3 OR EXTRACT(MONTH FROM B.DATETO)!=3) AND B.HOTELNO=H.HOTELNO AND B.ROOMNO=R.ROOMNO);

--QUESTION NUMBER : 31

SELECT HOTELNAME, SUM(UNOCCUPIED_DAYS*RATE) LOSS
FROM
(SELECT HOTELNO, ROOMNO, RATE,
CASE
    WHEN UNOCCUPIED_FOR IS NULL THEN 28
    ELSE UNOCCUPIED_FOR
END UNOCCUPIED_DAYS
FROM
(SELECT ROOM.ROOMNO, ROOM.HOTELNO, ROOM.RATE, UNOCCUPIED_FOR
FROM ROOM,
(SELECT HOTELNAME, ROOMNO, (28-SUM(OCCUPIED_FOR)) UNOCCUPIED_FOR FROM
(SELECT HOTELNAME, ROOMNO, RATE,
CASE
    WHEN (DATEFROM < '01-FEB-2014' AND DATETO < '01-FEB-2014')  THEN 0
    WHEN (EXTRACT(MONTH FROM DATEFROM) = 2 AND EXTRACT(MONTH FROM DATETO) = 2) THEN (DATETO-DATEFROM+1)
    WHEN (DATEFROM < '01-FEB-2014' AND EXTRACT(MONTH FROM DATETO) = 2)  THEN (DATETO - DATE '2014-02-01' + 1)
    WHEN (EXTRACT(MONTH FROM DATEFROM) = 2 AND DATETO > '28-FEB-2014') THEN (DATE '2014-02-28' - DATEFROM + 1)
    WHEN (DATEFROM > '28-FEB-2014' AND DATETO > '28-FEB-2014')  THEN 0
    ELSE 0
END OCCUPIED_FOR
FROM BOOKING NATURAL JOIN ROOM NATURAL JOIN HOTEL)
GROUP BY HOTELNAME, ROOMNO) B
WHERE ROOM.ROOMNO=B.ROOMNO(+)))
NATURAL JOIN
HOTEL
GROUP BY HOTELNAME HAVING HOTELNAME = 'HYATT';

