DROP TABLE EMPLOYEE_PCA;
DROP TABLE DEPARTMENT_PCA;

CREATE TABLE DEPARTMENT_PCA (
DEPTNO 	VARCHAR2(5),
DNAME	VARCHAR2(10)	NOT NULL,
LOC	VARCHAR2(10)	NOT NULL,
CONSTRAINT PK_PCA2_TABLE_100	PRIMARY KEY(DEPTNO),
CONSTRAINT CH_PCA2_TABLE_101	CHECK (DEPTNO LIKE 'D%')
);

CREATE TABLE EMPLOYEE_PCA (
EMPNO 	VARCHAR2(5),
ENAME	VARCHAR2(20)	NOT NULL,
JOB	VARCHAR2(10)	NOT NULL,
MGRNO	VARCHAR2(5),
HIREDATE   DATE,
SALARY	NUMBER(10,2)	NOT NULL,
COMM	NUMBER(2),
DEPTNO 	VARCHAR2(5),
CONSTRAINT PK_PCA2_TABLE_200	PRIMARY KEY(EMPNO),
CONSTRAINT CH_PCA2_TABLE_201	CHECK (EMPNO LIKE 'E%'),
CONSTRAINT FK_PCA2_TABLE_202	FOREIGN KEY(DEPTNO) REFERENCES DEPARTMENT_PCA(DEPTNO),
CONSTRAINT FK_PCA2_TABLE_203	FOREIGN KEY(MGRNO) REFERENCES EMPLOYEE_PCA(EMPNO)
ON DELETE CASCADE
);

INSERT INTO DEPARTMENT_PCA VALUES ('D100','CODING','KOLKATA');
INSERT INTO DEPARTMENT_PCA VALUES ('D101','SALEING','HOWRAH');
INSERT INTO DEPARTMENT_PCA VALUES ('D103','TESTING','HOOGHLY');
INSERT INTO DEPARTMENT_PCA VALUES ('D105','DEBUGGING','KOLKATA');
INSERT INTO DEPARTMENT_PCA VALUES ('D106','DESIGNER','SALT LAKE');
INSERT INTO DEPARTMENT_PCA VALUES ('D108','MANAGER','BANGALORE');
INSERT INTO DEPARTMENT_PCA VALUES ('D109','MARKETING','DELHI');

SELECT * FROM DEPARTMENT_PCA;


INSERT INTO EMPLOYEE_PCA VALUES ('E2000', 'DR. AJIT KUMAR', 'CEO', 'E2000', '14-DEC-1990', 85000, 50, 'D108' );
INSERT INTO EMPLOYEE_PCA VALUES ('E2001', 'SAIKAT PATHAK', 'TECH LEAD', 'E2000', '14-JAN-2012', 45000, 20, 'D100' );
INSERT INTO EMPLOYEE_PCA VALUES ('E2003', 'AVIK RAJAK', 'SALE DEPT', 'E2000', '2-FEB-2011', 50000, 30, 'D101' );
INSERT INTO EMPLOYEE_PCA VALUES ('E2004', 'MANISH DEY', 'TEST S/W', 'E2001', '14-DEC-2020', 55000, 20, 'D103' );
INSERT INTO EMPLOYEE_PCA VALUES ('E2007', 'RAHUL DAS', 'BUG FIX', 'E2001', '28-MAY-2005', 65000, 40, 'D105' );
INSERT INTO EMPLOYEE_PCA VALUES ('E2009', 'MINA ROY', 'DESIGNER', 'E2001', '08-JUNE-2009', 35000, 60, 'D106' );

SELECT * FROM EMPLOYEE_PCA;

--QUESTION : 01 (A)
SELECT OWNER, CONSTRAINT_NAME, CONSTRAINT_TYPE FROM USER_CONSTRAINTS WHERE TABLE_NAME='DEPARTMENT_PCA';

SELECT OWNER, CONSTRAINT_NAME, CONSTRAINT_TYPE FROM USER_CONSTRAINTS WHERE TABLE_NAME='EMPLOYEE_PCA';

--QUESTION : 01 (B)
UPDATE EMPLOYEE_PCA
SET SALARY=1.1*SALARY
WHERE (EXTRACT(YEAR FROM SYSDATE)-EXTRACT(YEAR FROM HIREDATE) > 10);

--QUESTION : 01 (C)
SELECT E1.ENAME, E2.ENAME
FROM EMPLOYEE_PCA E1, EMPLOYEE_PCA E2
WHERE (E1.MGRNO=E2.EMPNO);

--QUESTION : 01 (D)
SELECT DEPTNO, (CASE WHEN DEPTNO IN (SELECT DEPTNO FROM EMPLOYEE_PCA) THEN 'ACTIVE' ELSE 'NOT ACTIVE' END) "STATUS"
FROM DEPARTMENT_PCA;

--QUESTION : 01 (E)
SELECT EMPNO, ENAME , SALARY
FROM EMPLOYEE_PCA
WHERE (SALARY > (SELECT AVG(SALARY) FROM EMPLOYEE_PCA));

--QUESTION : 01 (F)
SELECT E.ENAME, D.DNAME
FROM EMPLOYEE_PCA E, DEPARTMENT_PCA D
WHERE (E.DEPTNO=D.DEPTNO(+));

--QUESTION : 01 (G)
DELETE FROM EMPLOYEE_PCA
WHERE (EXTRACT(YEAR FROM SYSDATE)-EXTRACT(YEAR FROM HIREDATE) > 30);







