drop table department;

CREATE TABLE DEPARTMENT(
DID VARCHAR2(10) CONSTRAINT PK_200 PRIMARY KEY,
DNAME VARCHAR2(20),
CONSTRAINT CH_200 CHECK (DID LIKE 'D%')
);


desc department;

/*
SELECT TABLE_NAME, CONSTRAINT_NAME, CONSTRAINT_TYPE
FROM USER_CONSTRAINTS
WHERE TABLE="DEPARTMENT";
*/


INSERT INTO DEPARTMENT VALUES ("D101","CSE"), ("D201","IT");

SELECT * FROM DEPARTMENT;


/*


DROP TABLE STUDENT;

CREATE TABLE STUDENT(
SID	VARCHAR2(10),
SNAME 	VARCHAR2(30),
DID 	VARCHAR2(10) CONSTRAINT FK_300 REFERENCES DEPARTMENT(DID),
AGE 	NUMBER(2),
SEX 	CHAR(1),
);

SELECT OWNER, TABLE_NAME, CONSTRAINT_NAME, CONSTRAINT_TYPE
FROM USER_CONSTRAINTS
WHERE TABLE="STUDENT";
*/

