--CREATE TABLE FROM ANOTHER TABLE

DROP TABLE STUDENT100;
DROP TABLE STUDENT200;

CREATE TABLE STUDENT100 AS SELECT * FROM STUDENT;

SELECT OWNER, TABLE_NAME, CONSTRAINT_NAME, CONSTRAINT_TYPE
FROM USER_CONSTRAINTS
WHERE TABLE_NAME='STUDENT100';

SELECT * FROM STUDENT100;

CREATE TABLE STUDENT200 AS SELECT * FROM STUDENT WHERE 1=0;

SELECT * FROM STUDENT200;

--ALTER COMMAND IN SQL
ALTER TABLE STUDENT DISABLE CONSTRAINTS PK_200;

--INSERT INTO STUDENT VALUES ('S1005', 'MINA ROY', 20, 'F', 'KOLKATA', 7908677689, 'D1002');

ALTER TABLE STUDENT ENABLE CONSTRAINTS PK_200;

--ALTER TABLE STUDENT DROP CONSTRAINTS PK_200;

ALTER TABLE STUDENT ADD COLUMN LOC VARCHAR2(20);
ALTER TABLE STUDENT DROP COLUMN LOC VARCHAR2(20);

ALTER TABLE STUDENT MODIFY MOBILE NUMBER(11);